# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'AFNetworking', '~> 2.5'

target 'smail-snapshots' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for smail-snapshots

end
